### ISSUE TITLE
Commas in calculator

### ISSUE THREAD

**Issue by mitdralla** [Lumenaut-Network/website#11]
Perhaps consider either limiting the input field to just numbers, or tweak the JS code which calculates the inflation amount as entering a comma produces incorrect calculations when commas are used. As an example, entering 10000 Lumens returns Estimated payout = 2.0488967 XLM which is correct. Where as entering 10,000 Lumens returns Estimated payout = 0.0020389 XLM.

You could do something like this:
`parseFloat(total.replace(/,/g, ''))`

**Comment by ZanderAdam** [comment]
@SeiryuZ @Lumenaut this one should be all set now :+1:
