### ISSUE TITLE
Not mobile friendly

### ISSUE THREAD

**Issue by janclarin** [Lumenaut-Network/website#3]
If people open up the site on their phones (e.g. after seeing it on reddit), they need to be able to see how easy it is to switch over or what Lumenaut is for. The better the initial experience, the more likely they are going to take out their computer and actually make the switch over to the inflation pool.

See iPhone screenshot:
![image](https://user-images.githubusercontent.com/2449384/35032281-33f377ca-fb1b-11e7-8fd1-e5e86c25d81a.png)

**Comment by ZanderAdam** [comment]
@Lumenaut look like PR comments dont auto close issues, could be my perms. 

This one can be closed. Fixed in #6

**Comment by SeiryuZ** [comment]
Thank you @ZanderAdam
