### ISSUE TITLE
Some well intended verbiage does the opposite of inspiring confidence/safety

### ISSUE THREAD

**Issue by amitailanciano** [Lumenaut-Network/website#7]
Hey all, thanks for the hard work and for putting this together - I only have one minor criticism. I feel that the verbiage in the "Why use the community pool" section of the site regarding safety raises more qualms than puts to rest uncertainty.

> By joining our pool you will not encounter any problem and you will not lose any of your Lumens.

Perhaps explain how/why this is the case instead of loosely claiming it. What procedures do you have in place to assert this? Also maybe explain how Lumens are typically scammed/stolen with other pools and how you are different (asking for private keys, etc).

> Everything is 100% safe!

Let the quality of your website and its contents do the talking, I think this makes people question safety more than putting them at ease.

**Comment by Lumenaut** [comment]
I agree! Thanks for your opinion. I will review the text and change it. I will also restructure the website a little. Best regards.
